#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ]; then
    export PREFIX="venv/bin/"
    export PATH=${PREFIX}:${PATH}
fi
export SOURCE_FILES="uvicorn_worker tests"

set -x

${PREFIX}ruff format --check --diff $SOURCE_FILES
${PREFIX}mypy $SOURCE_FILES
${PREFIX}ruff check $SOURCE_FILES
